# This project was developed with assistance from AI tools.
{{- if .Values.ngc.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: ngc-pull-secret
  namespace: {{ include "isaac-sim-streaming.namespace" . }}
  labels:
    {{- include "isaac-sim-streaming.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":"%s"}}}` .Values.ngc.apiKey | b64enc }}
{{- end }}
